/*
import axios from 'axios';

export default axios.create({
  baseURL: 'http://euclid.nmu.edu:8155/api',
});
*/

export default {
  get(arg) {
    if (arg === '/birds/') {
      return Promise.resolve([{
        bagAndBirdWeight: 22.5,
        bagWeight: 12.3,
        bandCombo: 'g0/Y#',
        bandNumber: '2830-56001',
        banders: 'Lindsay, Szarmach',
        bibWidth: 0.0,
        billDepth: 3.5,
        billLength: 10.3,
        billWidth: 3.4,
        birdWeight: 10.2,
        capLength: 0.0,
        captureSite: 'Carpenter Net',
        captureTimestamp: 1507296600,
        image: null,
        legLeftBottom: '#',
        legLeftTop: 'Y',
        legRightBottom: null,
        legRightTop: 'g0',
        logTimestamp: 1507579380,
        longestSecondary: 54,
        netEnterTimestamp: 1507262400,
        netExitTimestamp: 1507262400,
        notes: 'hallux 8.8',
        releasedTimestamp: 1507262400,
        rfid: '011016A269',
        species: 'RBNU',
        suspectedSex: 'female',
        tailLength: 37,
        tarsusLength: 16.5,
        tissueSample: 'feather',
        weather: 'Clear, 55F',
        wingChordLength: 66,
      },
      {
        bagAndBirdWeight: 24.5,
        bagWeight: 12.25,
        bandCombo: 'N#/g0',
        bandNumber: '2830-56013',
        banders: 'Lindsay, VanOrman',
        bibWidth: 24.2,
        billDepth: 3.8,
        billLength: 6.1,
        billWidth: 3.6,
        birdWeight: 12.25,
        capLength: 33.3,
        captureSite: 'Cliffside Net',
        captureTimestamp: 1507530600,
        image: null,
        legLeftBottom: null,
        legLeftTop: 'g0',
        legRightBottom: '#',
        legRightTop: 'N',
        logTimestamp: 1508525400,
        longestSecondary: 56,
        netEnterTimestamp: 1507521600,
        netExitTimestamp: 1507521600,
        notes: '',
        releasedTimestamp: 1507521600,
        rfid: '011016A352',
        species: 'BCCH',
        suspectedSex: 'unknown',
        tailLength: 70,
        tarsusLength: 16.6,
        tissueSample: 'feather',
        weather: 'clear, 65 F',
        wingChordLength: 66,
      },
      {
        bagAndBirdWeight: 22.75,
        bagWeight: 12.3,
        bandCombo: 'B#/i0',
        bandNumber: '2830-56002',
        banders: 'Lindsay, Szarmach',
        bibWidth: 22.5,
        billDepth: 3.7,
        billLength: 5.1,
        billWidth: 3.5,
        birdWeight: 10.45,
        capLength: 32.5,
        captureSite: 'Carpenter Net',
        captureTimestamp: 1507296600,
        image: null,
        legLeftBottom: null,
        legLeftTop: 'i0',
        legRightBottom: '#',
        legRightTop: 'B',
        logTimestamp: 1507579560,
        longestSecondary: 54,
        netEnterTimestamp: 1507262400,
        netExitTimestamp: 1507262400,
        notes: 'molting R6, R6 photos taken',
        releasedTimestamp: 1507262400,
        rfid: '011016A4D4',
        species: 'BCCH',
        suspectedSex: 'unknown',
        tailLength: 61,
        tarsusLength: 17.7,
        tissueSample: 'feather',
        weather: 'Clear, 55F',
        wingChordLength: 63,
      }]);
    } else if (arg === '/visits/') {
      return Promise.resolve([
        {
          rfid: 'TAA',
          feederID: 'CLIF',
          visitTimestamp: 1492873308,
          temperature: 44,
          mass: 108,
        },
        {
          rfid: 'TACOO',
          feederID: 'CLIF',
          visitTimestamp: 1492873308,
          temperature: 44,
          mass: 108,
        },
        {
          rfid: 'TACCCOO',
          feederID: 'CLIF',
          visitTimestamp: 1492873308,
          temperature: 44,
          mass: 108,
        },
      ]);
    }
    return Promise.resolve([]);
  },
};
